apiVersion: v1
kind: Service
metadata:
  name: horilla-service
  namespace: hr-system
spec:
  type: NodePort
  selector:
    app: horilla
  ports:
  - protocol: TCP
    port: 8000       # Port im Container
    targetPort: 8000 # Zielport im Container
    nodePort: 30700
